P5/ej2/config/routes.rb
Rails.application.routes.draw do
  resources :kings
  root to: 'polite#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

P5/ej2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

P5/ej2/app/models/king.rb
class King < ApplicationRecord
	validates :name, presence: true
	
	def to_s
		name
	end

end

P5/ej2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

P5/ej2/app/controllers/home_controller.rb
class HomeController < ApplicationController
	 before_action only: [:show, :edit, :update, :destroy]

	def index
    	@custom = APP_CUSTOM
  	end

end

P5/ej2/app/controllers/kings_controller.rb
class KingsController < ApplicationController
  before_action :set_king, only: [:show, :edit, :update, :destroy]

  # GET /kings
  # GET /kings.json
  def index
    @kings = King.all
  end

  # GET /kings/1
  # GET /kings/1.json
  def show
  end

  # GET /kings/new
  def new
    @king = King.new
  end

  # GET /kings/1/edit
  def edit
  end

  # POST /kings
  # POST /kings.json
  def create
    @king = King.new(king_params)

    respond_to do |format|
      if @king.save
        format.html { redirect_to @king, notice: 'King was successfully created.' }
        format.json { render :show, status: :created, location: @king }
      else
        format.html { render :new }
        format.json { render json: @king.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kings/1
  # PATCH/PUT /kings/1.json
  def update
    respond_to do |format|
      if @king.update(king_params)
        format.html { redirect_to @king, notice: 'King was successfully updated.' }
        format.json { render :show, status: :ok, location: @king }
      else
        format.html { render :edit }
        format.json { render json: @king.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kings/1
  # DELETE /kings/1.json
  def destroy
    @king.destroy
    respond_to do |format|
      format.html { redirect_to kings_url, notice: 'King was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_king
      @king = King.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def king_params
      params.require(:king).permit(:name, :kingdom, :date_since, :date_until)
    end
end

P5/ej2/app/controllers/polite_controller.rb
class PoliteController < ApplicationController
	before_action only: [:show, :edit, :update, :destroy]
	
	attr_accessor :salutes

	def initialize
		self.salutes = ['hola','crack','como','estas','hoy?']
	end

	def index
    	@salute = self.salutes[rand(0..4)]
  	end

end

P5/ej2/app/helpers/application_helper.rb
module ApplicationHelper
end

P5/ej2/app/helpers/home_helper.rb
module HomeHelper
end

P5/ej2/app/helpers/kings_helper.rb
module KingsHelper
end

P5/ej2/app/helpers/polite_helper.rb
module PoliteHelper
end

P5/ej2/app/views/application/_navigation.html.erb
<nav class="navbar navbar-light bg-faded">
 <a href="#" class="navbar-brand">KingsApp</a>
 <div class="nav navbar-nav">
 <%= link_to 'Kings', kings_path, class: 'nav-item nav-link' -%>
 </div>
</nav>

P5/ej2/app/views/home/index.html.erb
<h1>Index..</h1>
<h3> <%= @custom %> </h3>

P5/ej2/app/views/kings/_form.html.erb
<%= simple_form_for @king do |f| %>
  <%= f.input :name, label: 'King name please', error: 'King name is mandatory'%>
  <%= f.input :kingdom %>
  <%= f.input :date_since, as: :date %>
  <%= f.input :date_until, as: :date %>
  <%= f.button :submit %>
<% end %>

P5/ej2/app/views/kings/edit.html.erb
<h1>Editing King</h1>

<%= render 'form', king: @king %>

<%= link_to 'Show', @king %> |
<%= link_to 'Back', kings_path %>

P5/ej2/app/views/kings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Kings</h1>
<h2><%= t(:hello) %></h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Kingdom</th>
      <th>Date since</th>
      <th>Date until</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kings.each do |king| %>
      <tr>
        <td><%= king.name %></td>
        <td><%= king.kingdom %></td>
        <td><%= king.date_since %></td>
        <td><%= king.date_until %></td>
        <td><%= link_to 'Show', king %></td>
        <td><%= link_to 'Edit', edit_king_path(king) %></td>
        <td><%= link_to 'Destroy', king, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New King', new_king_path, :class => 'btn btn-success btn-lg' %>

P5/ej2/app/views/kings/new.html.erb
<h1>New King</h1>

<%= render 'form', king: @king %>

<%= link_to 'Back', kings_path %>

P5/ej2/app/views/kings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @king.name %>
</p>

<p>
  <strong>Kingdom:</strong>
  <%= @king.kingdom %>
</p>

<p>
  <strong>Date since:</strong>
  <%= @king.date_since %>
</p>

<p>
  <strong>Date until:</strong>
  <%= @king.date_until %>
</p>

<%= link_to 'Edit', edit_king_path(@king) %> |
<%= link_to 'Back', kings_path %>

P5/ej2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ej2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'navigation' %>
  	<div class="container">	
    	<%= yield %>
  	</div>
  </body>
</html>

P5/ej2/app/views/polite/index.html.erb
<h1>Saludo!</h1>
<h3> <%= @salute %> </h3>